name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli: 
        description: Run by cypress node command
        default: node runner.js

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: yarn install

      - name: Run E2E teste headlessly
        run:  ${{github.event.inputs.cli}}
